version: "3.8"
services:
  sportsstore:
    build: .
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__SportsStoreConnection=Server=sqlserver;Database=SportsStore;User=sa;Password=YourPassword123;TrustServerCertificate=true;
      - ConnectionStrings__IdentityConnection=Server=sqlserver;Database=Identity;User=sa;Password=YourPassword123;TrustServerCertificate=true;
    depends_on:
      - sqlserver

  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      SA_PASSWORD: "YourPassword123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"